/**
 * 100 products equally distributed across 12 categories.
 * Used by the database seed script.
 */

export const SEED_PRODUCTS: { title: string; category: string; basePrice: number }[] = [
  // Laptops (9)
  { title: "MacBook Air M3 13\" 256GB - Midnight", category: "Laptops", basePrice: 1099 },
  { title: "Dell XPS 15 - Intel i7, 16GB RAM, 512GB SSD", category: "Laptops", basePrice: 1299 },
  { title: "Lenovo ThinkPad X1 Carbon Gen 11", category: "Laptops", basePrice: 1499 },
  { title: "ASUS ZenBook 14 OLED - Ryzen 7", category: "Laptops", basePrice: 899 },
  { title: "HP Spectre x360 14\" 2-in-1 Convertible", category: "Laptops", basePrice: 1199 },
  { title: "Microsoft Surface Laptop 5 13.5\"", category: "Laptops", basePrice: 999 },
  { title: "Acer Swift X 14\" Creator Laptop", category: "Laptops", basePrice: 799 },
  { title: "Razer Blade 14 Gaming Laptop", category: "Laptops", basePrice: 2399 },
  { title: "Framework Laptop 16 DIY Edition", category: "Laptops", basePrice: 1399 },
  // Monitors (8)
  { title: "LG 27\" 4K UHD IPS Monitor (27UP850-W)", category: "Monitors", basePrice: 399 },
  { title: "Samsung 32\" Odyssey G7 Curved Gaming Monitor", category: "Monitors", basePrice: 599 },
  { title: "Dell UltraSharp U2723QE 27\" 4K USB-C Monitor", category: "Monitors", basePrice: 549 },
  { title: "ASUS ProArt PA278QV 27\" WQHD Monitor", category: "Monitors", basePrice: 319 },
  { title: "BenQ PD2705U 27\" 4K Designer Monitor", category: "Monitors", basePrice: 479 },
  { title: "LG 34\" UltraWide Curved Monitor", category: "Monitors", basePrice: 449 },
  { title: "AOC 27\" Gaming Monitor 165Hz", category: "Monitors", basePrice: 249 },
  { title: "ViewSonic 32\" 4K UHD Monitor", category: "Monitors", basePrice: 349 },
  // Phones (9)
  { title: "iPhone 15 Pro 256GB - Natural Titanium", category: "Phones", basePrice: 999 },
  { title: "Samsung Galaxy S24 Ultra 512GB", category: "Phones", basePrice: 1299 },
  { title: "Google Pixel 8 Pro 128GB - Obsidian", category: "Phones", basePrice: 799 },
  { title: "OnePlus 12 256GB - Silky Black", category: "Phones", basePrice: 699 },
  { title: "iPhone 14 128GB - Midnight", category: "Phones", basePrice: 699 },
  { title: "Samsung Galaxy Z Flip 5", category: "Phones", basePrice: 999 },
  { title: "Google Pixel 8 128GB", category: "Phones", basePrice: 549 },
  { title: "Nothing Phone 2", category: "Phones", basePrice: 599 },
  { title: "Motorola Edge+ 2023", category: "Phones", basePrice: 599 },
  // Keyboards (8)
  { title: "Keychron K2 Wireless Mechanical Keyboard", category: "Keyboards", basePrice: 79 },
  { title: "Logitech MX Keys S - Wireless Keyboard", category: "Keyboards", basePrice: 99 },
  { title: "Razer BlackWidow V4 Pro Mechanical Keyboard", category: "Keyboards", basePrice: 229 },
  { title: "Apple Magic Keyboard with Touch ID", category: "Keyboards", basePrice: 149 },
  { title: "SteelSeries Apex Pro TKL Gaming Keyboard", category: "Keyboards", basePrice: 179 },
  { title: "Corsair K70 RGB Pro Mechanical Keyboard", category: "Keyboards", basePrice: 169 },
  { title: "Keychron Q1 Pro Wireless Mechanical Keyboard", category: "Keyboards", basePrice: 199 },
  { title: "HyperX Alloy Origins Core", category: "Keyboards", basePrice: 89 },
  // Audio (9)
  { title: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones", category: "Audio", basePrice: 349 },
  { title: "Apple AirPods Pro (2nd Gen)", category: "Audio", basePrice: 249 },
  { title: "Bose QuietComfort Ultra Wireless Headphones", category: "Audio", basePrice: 429 },
  { title: "Sennheiser Momentum 4 Wireless", category: "Audio", basePrice: 299 },
  { title: "Samsung Galaxy Buds2 Pro", category: "Audio", basePrice: 229 },
  { title: "Sony WF-1000XM5 True Wireless Earbuds", category: "Audio", basePrice: 299 },
  { title: "Bose QuietComfort Earbuds II", category: "Audio", basePrice: 249 },
  { title: "JBL Tour One M2 Wireless Headphones", category: "Audio", basePrice: 279 },
  { title: "Beats Studio Pro Wireless Headphones", category: "Audio", basePrice: 349 },
  // Tablets (8)
  { title: "iPad Pro 12.9\" M2 256GB", category: "Tablets", basePrice: 1099 },
  { title: "iPad Air 10.9\" M1 64GB", category: "Tablets", basePrice: 599 },
  { title: "Samsung Galaxy Tab S9 11\"", category: "Tablets", basePrice: 799 },
  { title: "Microsoft Surface Pro 9", category: "Tablets", basePrice: 999 },
  { title: "Amazon Fire HD 10 Tablet", category: "Tablets", basePrice: 139 },
  { title: "Lenovo Tab P11 Pro Gen 2", category: "Tablets", basePrice: 449 },
  { title: "OnePlus Pad", category: "Tablets", basePrice: 479 },
  { title: "Google Pixel Tablet", category: "Tablets", basePrice: 499 },
  // Smartwatches (9)
  { title: "Apple Watch Ultra 2", category: "Smartwatches", basePrice: 799 },
  { title: "Samsung Galaxy Watch 6 44mm", category: "Smartwatches", basePrice: 299 },
  { title: "Garmin Fenix 7 Sapphire Solar", category: "Smartwatches", basePrice: 799 },
  { title: "Apple Watch Series 9 GPS 45mm", category: "Smartwatches", basePrice: 429 },
  { title: "Fitbit Sense 2", category: "Smartwatches", basePrice: 249 },
  { title: "Garmin Forerunner 265", category: "Smartwatches", basePrice: 449 },
  { title: "Samsung Galaxy Watch 6 Classic", category: "Smartwatches", basePrice: 399 },
  { title: "Google Pixel Watch 2", category: "Smartwatches", basePrice: 349 },
  { title: "Amazfit GTR 4", category: "Smartwatches", basePrice: 229 },
  // Cameras (8)
  { title: "Sony A7 IV Full-Frame Mirrorless Camera", category: "Cameras", basePrice: 2498 },
  { title: "Canon EOS R6 II Mirrorless Camera", category: "Cameras", basePrice: 2499 },
  { title: "Nikon Z8 Mirrorless Camera", category: "Cameras", basePrice: 3999 },
  { title: "Fujifilm X-T5 Mirrorless Camera", category: "Cameras", basePrice: 1699 },
  { title: "Sony A6700 APS-C Mirrorless Camera", category: "Cameras", basePrice: 1398 },
  { title: "Canon EOS R50 Mirrorless Camera", category: "Cameras", basePrice: 679 },
  { title: "GoPro Hero 12 Black", category: "Cameras", basePrice: 399 },
  { title: "DJI Osmo Pocket 3", category: "Cameras", basePrice: 519 },
  // Storage (8)
  { title: "Samsung 990 Pro 2TB NVMe SSD", category: "Storage", basePrice: 179 },
  { title: "WD Black SN850X 2TB NVMe SSD", category: "Storage", basePrice: 169 },
  { title: "Crucial P5 Plus 2TB NVMe SSD", category: "Storage", basePrice: 149 },
  { title: "SanDisk Extreme Pro 2TB Portable SSD", category: "Storage", basePrice: 199 },
  { title: "Samsung T7 Portable SSD 2TB", category: "Storage", basePrice: 149 },
  { title: "Seagate FireCuda 530 2TB NVMe", category: "Storage", basePrice: 189 },
  { title: "WD My Book 8TB External HDD", category: "Storage", basePrice: 179 },
  { title: "LaCie Rugged USB-C 5TB", category: "Storage", basePrice: 189 },
  // Gaming (9)
  { title: "PlayStation 5 Console", category: "Gaming", basePrice: 499 },
  { title: "Xbox Series X Console", category: "Gaming", basePrice: 499 },
  { title: "Nintendo Switch OLED Model", category: "Gaming", basePrice: 349 },
  { title: "Steam Deck 512GB", category: "Gaming", basePrice: 649 },
  { title: "Sony DualSense Wireless Controller", category: "Gaming", basePrice: 69 },
  { title: "Xbox Wireless Controller", category: "Gaming", basePrice: 59 },
  { title: "Razer Kraken V3 Pro Wireless", category: "Gaming", basePrice: 199 },
  { title: "Logitech G Pro X Wireless Headset", category: "Gaming", basePrice: 199 },
  { title: "ASUS ROG Strix Scope II 96 Wireless", category: "Gaming", basePrice: 179 },
  // Components (8)
  { title: "AMD Ryzen 9 7950X3D Desktop Processor", category: "Components", basePrice: 599 },
  { title: "Intel Core i9-14900K Desktop Processor", category: "Components", basePrice: 589 },
  { title: "NVIDIA GeForce RTX 4090 Founders Edition", category: "Components", basePrice: 1599 },
  { title: "AMD Radeon RX 7900 XTX Graphics Card", category: "Components", basePrice: 999 },
  { title: "Corsair Vengeance 32GB DDR5 6000MHz", category: "Components", basePrice: 129 },
  { title: "Samsung 980 Pro 2TB NVMe SSD", category: "Components", basePrice: 149 },
  { title: "ASUS ROG Strix B650E-F Gaming Motherboard", category: "Components", basePrice: 289 },
  { title: "NZXT Kraken X73 360mm AIO Cooler", category: "Components", basePrice: 229 },
  // TVs (8)
  { title: "LG C3 55\" OLED 4K Smart TV", category: "TVs", basePrice: 1296 },
  { title: "Samsung S90C 65\" OLED 4K Smart TV", category: "TVs", basePrice: 1597 },
  { title: "Sony A80L 55\" OLED 4K Smart TV", category: "TVs", basePrice: 1398 },
  { title: "TCL 6-Series 65\" 4K QLED Roku TV", category: "TVs", basePrice: 899 },
  { title: "Hisense U8K 65\" 4K Mini-LED TV", category: "TVs", basePrice: 898 },
  { title: "Vizio M-Series 65\" 4K Smart TV", category: "TVs", basePrice: 598 },
  { title: "Roku Plus 65\" 4K QLED TV", category: "TVs", basePrice: 699 },
  { title: "Samsung The Frame 55\" 4K TV", category: "TVs", basePrice: 1497 },
];
